+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Mon May 26 08:47:17 2025 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL aide
+ pkgs=aide
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs aide --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp_3xmmkn4
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp_3xmmkn4
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Mon May 26 08:47:19 2025 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Mon May 26 08:47:19 2025 - INFO  - Start to run test.
+ aide --init
Start timestamp: 2025-05-26 08:47:19 +0000 (AIDE 0.17.4)
AIDE initialized database at /var/lib/aide/aide.db.new.gz

Number of entries:	52943

---------------------------------------------------
The attributes of the (uncompressed) database(s):
---------------------------------------------------

/var/lib/aide/aide.db.new.gz
 MD5       : nAFpWqFTr12HNTx0FYsaNQ==
 SHA1      : f1APRDLqZIvNEwZCiKSeMrcdXy8=
 SHA256    : tN0jPkhBMiHmv2xpex44vMZZNhwImSj1
             0i650hMv8Qk=
 SHA512    : qvykvc3VdTUutwuaYSPnx6LdkbL7N69E
             FF4HY8KSGIslWcIj3Tugt8a36De0Ho1l
             NRy4CekXmMta0ACmRLVUCw==
 RMD160    : B6b5/unUa4EUbg9oE5dYSovQ4Ko=
 TIGER     : cbgDzYbHdg7CpjQcbeJi/VUV0YoDQ2hN
 CRC32     : ap35gQ==
 WHIRLPOOL : XPaGovqsIYM2B+ZXxDE9kK/AE1/p5F9k
             +4mi2eGyw+NpYCV1SQa3XU+vYmhJw89f
             By/rizlWQKL6p+9/AbkFWg==
 GOST      : rW4fzy88IM3H3OoNVX4XjYUHDbx7bwst
             C1cy4XaY7Po=
 STRIBOG256: f7k7yhUofoYo91pvIqdcUuRVBeXQhjJ2
             H6aEp3m5Orw=
 STRIBOG512: W0l96/W9DUhdxnKbEtnjvKq7eaD1NbL/
             vMr3pepTMbDmPGL8IhqKDTMmwANfquDu
             Yq4qJuX351cPpTC+sHKcuA==
 SM3       : 07JtFg/ck2R6j0B2Tcn19KzF0/0CMwp/
             Sh+qgM+woUo=


End timestamp: 2025-05-26 08:47:46 +0000 (run time: 0m 27s)
+ CHECK_RESULT 0 0 0 'initialization failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='initialization failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
+ useradd testuser
+ aide -c /etc/aide.conf --update
+ grep -A 10 'Changed entries:'
+ grep /etc/group
f > ... mci.H..  : /etc/group
f < ... mc..H..  : /etc/group-
+ CHECK_RESULT 0 0 0 'Update execution failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Update execution failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ test -f /var/lib/aide/aide.db.new.gz
+ CHECK_RESULT 0 0 0 'Update execution failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Update execution failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
+ aide --check
+ grep Changed entries:
grep: entries:: No such file or directory
+ CHECK_RESULT 2 0 1 'Check execution failed'
+ actual_result=2
+ expect_result=0
+ mode=1
+ error_log='Check execution failed'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 1 -eq 0 ']'
+ test 2x == 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Mon May 26 08:49:11 2025 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Mon May 26 08:49:11 2025 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Mon May 26 08:49:11 2025 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp_3xmmkn4 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp_3xmmkn4
+ '[' 0 -ne 0 ']'
+ userdel -rf testuser
+ rm -rf testlog /var/log/aide/aide.log /var/lib/aide/aide.db.gz
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Mon May 26 08:49:12 2025 - INFO  - End to restore the test environment.
