+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ source ./common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ ARRAY_PROFILE=("arm-native-android-container-robox" "basic-test-suite-baseline-fio" "basic-test-suite-baseline-lmbench" "basic-test-suite-baseline-netperf" "basic-test-suite-baseline-stream" "basic-test-suite-baseline-unixbench" "basic-test-suite-speccpu-speccpu2006" "basic-test-suite-specjbb-specjbb2015" "big-data-hadoop-hdfs-dfsio-hdd" "big-data-hadoop-hdfs-dfsio-ssd" "big-data-hadoop-spark-bayesian" "big-data-hadoop-spark-kmeans" "big-data-hadoop-spark-sql1" "big-data-hadoop-spark-sql10" "big-data-hadoop-spark-sql2" "big-data-hadoop-spark-sql3" "big-data-hadoop-spark-sql4" "big-data-hadoop-spark-sql5" "big-data-hadoop-spark-sql6" "big-data-hadoop-spark-sql7" "big-data-hadoop-spark-sql8" "big-data-hadoop-spark-sql9" "big-data-hadoop-spark-tersort" "big-data-hadoop-spark-wordcount" "cloud-compute-kvm-host" "database-mariadb-2p-tpcc-c3" "database-mariadb-4p-tpcc-c3" "database-mongodb-2p-sysbench" "database-mysql-2p-sysbench-hdd" "database-mysql-2p-sysbench-ssd" "database-postgresql-2p-sysbench-hdd" "database-postgresql-2p-sysbench-ssd" "default-default" "docker-mariadb-2p-tpcc-c3" "docker-mariadb-4p-tpcc-c3" "hpc-gatk4-human-genome" "in-memory-database-redis-redis-benchmark" "middleware-dubbo-dubbo-benchmark" "storage-ceph-vdbench-hdd" "storage-ceph-vdbench-ssd" "virtualization-consumer-cloud-olc" "virtualization-mariadb-2p-tpcc-c3" "virtualization-mariadb-4p-tpcc-c3" "web-apache-traffic-server-spirent-pingpo" "web-nginx-http-long-connection" "web-nginx-https-short-connection")
++ ARRAY_SERVICE=("arm-native" "basic-test-suite" "big-data" "cloud-compute" "database" "default" "docker" "hpc" "in-memory-database" "middleware" "storage" "virtualization" "web")
++ SPECIAL_CHARACTERS='~\!@#%^*'
++ ULTRA_LONG_CHARACTERS=0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
+ test_service=test_service
+ test_app=test_app
+ test_scenario=test_scenario
+ profile_path=./common/example.conf
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Thu May 25 22:35:38 2023 - INFO  - Start environment preparation.
+ deploy_autund
+ DNF_INSTALL 'atune  atune-engine'
+ pkgs='atune  atune-engine'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'atune  atune-engine' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpz_wmvnm1
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpz_wmvnm1
++ lsblk
++ grep disk
++ awk 'NR==1{print $1}'
+ disk_name=vda
+ cp /etc/atuned/atuned.cnf /etc/atuned/atuned.cnf.bak
+ cp /etc/atuned/engine.cnf /etc/atuned/engine.cnf.bak
+ sed -i 's/^disk =.*/disk = vda/g' /etc/atuned/atuned.cnf
+ sed -i 's/^network =.*/network = /g' /etc/atuned/atuned.cnf
+ sed -i 's/rest_tls = true/rest_tls = false/g' /etc/atuned/atuned.cnf
+ sed -i 's/engine_tls = true/engine_tls = false/g' /etc/atuned/atuned.cnf
+ sed -i 's/engine_tls = true/engine_tls = false/g' /etc/atuned/engine.cnf
+ creat_ca
+ CERT_PATH=demo
+ mkdir demo
mkdir: cannot create directory ‘demo’: File exists
+ openssl genrsa -out demo/ca.key 2048
+ openssl req -new -x509 -days 3650 -subj /CN=ca -key demo/ca.key -out demo/ca.crt
+ IP_ADDR=localhost
+ openssl genrsa -out demo/server.key 2048
+ cp /etc/pki/tls/openssl.cnf demo
+ test localhost == localhost
+ echo '[SAN]\nsubjectAltName=DNS:localhost'
+ echo subjectAltName=DNS:localhost
+ openssl req -new -subj /CN=localhost -config demo/openssl.cnf -key demo/server.key -out demo/server.csr
+ openssl x509 -req -sha256 -CA demo/ca.crt -CAkey demo/ca.key -CAcreateserial -days 3650 -extfile demo/extfile.cnf -in demo/server.csr -out demo/server.crt
Certificate request self-signature ok
subject=CN = localhost
+ rm -rf demo/ca.srl demo/server.csr demo/extfile.cnf demo/openssl.cnf
+ IP_ADDR=localhost
+ openssl genrsa -out demo/client.key 2048
+ cp /etc/pki/tls/openssl.cnf demo
+ test localhost == localhost
+ echo '[SAN]\nsubjectAltName=DNS:localhost'
+ echo subjectAltName=DNS:localhost
+ openssl req -new -subj /CN=localhost -config demo/openssl.cnf -key demo/client.key -out demo/client.csr
+ openssl x509 -req -sha256 -CA demo/ca.crt -CAkey demo/ca.key -CAcreateserial -days 3650 -extfile demo/extfile.cnf -in demo/client.csr -out demo/client.crt
Certificate request self-signature ok
subject=CN = localhost
+ rm -rf demo/ca.srl demo/client.csr demo/extfile.cnf demo/openssl.cnf
++ pwd
+ cp -ar /root/mugen/testcases/cli-test/atune/demo/ca.crt demo/server.crt demo/server.key /etc/atuned/rest_certs/
++ pwd
+ cp -ar /root/mugen/testcases/cli-test/atune/demo/ca.crt demo/client.crt demo/client.key /etc/atuned/engine_certs/
++ pwd
+ cp -ar /root/mugen/testcases/cli-test/atune/demo/ca.crt demo/server.crt demo/server.key /etc/atuned/engine_certs/
+ systemctl start atuned
Job for atuned.service failed because the control process exited with error code.
See "systemctl status atuned.service" and "journalctl -xeu atuned.service" for details.
+ systemctl status atuned
+ grep running
+ CHECK_RESULT 1 0 0 'atuned service startup failure'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atuned service startup failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atuned service startup failure'
+ LOG_ERROR 'atuned service startup failure'
+ message='atuned service startup failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atuned service startup failure'
Thu May 25 22:40:00 2023 - ERROR - atuned service startup failure
+ (( exec_result++ ))
+ LOG_ERROR './common/common_lib.sh line 40'
+ message='./common/common_lib.sh line 40'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message './common/common_lib.sh line 40'
Thu May 25 22:40:01 2023 - ERROR - ./common/common_lib.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start atune-engine
+ systemctl status atune-engine
+ grep running
     Active: active (running) since Thu 2023-05-25 22:40:01 CST; 205ms ago
+ CHECK_RESULT 0 0 0 'atune-engine service startup failure'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='atune-engine service startup failure'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu May 25 22:40:02 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ atune-adm define test_service test_app test_scenario ./common/example.conf
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep test_service temp.log
+ grep test_app-test_scenario
+ CHECK_RESULT 1 0 0 'atune-adm define command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-adm define command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-adm define command execution failed'
+ LOG_ERROR 'atune-adm define command execution failed'
+ message='atune-adm define command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-adm define command execution failed'
Thu May 25 22:40:03 2023 - ERROR - atune-adm define command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 37'
+ message='oe_test_service_atuned_04.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 37'
Thu May 25 22:40:04 2023 - ERROR - oe_test_service_atuned_04.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ atune-adm undefine test_service-test_app-test_scenario
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ atune-adm list
failed to dial "/var/run/atuned/atuned.sock" : connection error: desc = "transport: error while dialing: dial unix /var/run/atuned/atuned.sock: connect: connection refused"
+ grep test_service temp.log
+ grep test_app-test_scenario
+ CHECK_RESULT 1 1 0 'atune-adm undefine command execution failed'
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log='atune-adm undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ atune-adm undefine -h
+ grep 'delete the specified profile' temp.log
   atune-adm undefine - delete the specified profile
   delete the specified profile.
+ CHECK_RESULT 0 0 0 'atune-adm undefine -h command execution failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='atune-adm undefine -h command execution failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ (( i=0 ))
+ (( i<46 ))
+ atune-adm undefine arm-native-android-container-robox
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:05 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:06 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:07 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:07 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine basic-test-suite-baseline-fio
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:08 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:09 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:10 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:10 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine basic-test-suite-baseline-lmbench
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:11 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:12 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:12 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:13 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine basic-test-suite-baseline-netperf
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:14 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:14 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:15 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:15 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine basic-test-suite-baseline-stream
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:16 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:17 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:17 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:18 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine basic-test-suite-baseline-unixbench
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:18 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:19 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:20 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:20 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine basic-test-suite-speccpu-speccpu2006
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:21 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:22 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:22 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:23 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine basic-test-suite-specjbb-specjbb2015
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:23 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:24 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:25 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:25 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-hdfs-dfsio-hdd
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:26 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:27 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:27 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:28 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-hdfs-dfsio-ssd
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:29 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:29 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:30 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:30 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-bayesian
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:31 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:32 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:32 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:33 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-kmeans
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:34 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:34 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:35 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:35 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-sql1
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:36 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:37 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:37 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:38 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-sql10
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:39 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:39 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:40 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:41 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-sql2
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:41 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:42 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:43 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:43 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-sql3
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:44 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:44 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:45 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:46 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-sql4
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:46 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:47 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:47 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:48 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-sql5
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:49 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:49 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:50 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:50 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-sql6
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:51 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:52 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:52 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:53 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-sql7
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:54 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:54 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:55 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:55 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-sql8
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:56 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:57 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:40:57 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:40:58 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-sql9
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:40:59 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:40:59 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:00 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:00 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-tersort
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:01 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:02 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:02 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:03 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine big-data-hadoop-spark-wordcount
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:04 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:04 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:05 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:05 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine cloud-compute-kvm-host
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:06 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:07 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:07 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:08 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine database-mariadb-2p-tpcc-c3
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:09 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:09 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:10 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:10 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine database-mariadb-4p-tpcc-c3
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:11 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:11 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:12 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:12 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine database-mongodb-2p-sysbench
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:13 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:14 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:14 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:15 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine database-mysql-2p-sysbench-hdd
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:16 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:16 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:17 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:17 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine database-mysql-2p-sysbench-ssd
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:18 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:19 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:19 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:20 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine database-postgresql-2p-sysbench-hdd
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:21 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:21 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:22 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:22 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine database-postgresql-2p-sysbench-ssd
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:23 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:24 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:24 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:25 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine default-default
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:26 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:26 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:27 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:27 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine docker-mariadb-2p-tpcc-c3
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:28 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:29 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:29 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:30 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine docker-mariadb-4p-tpcc-c3
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:31 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:31 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:32 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:32 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine hpc-gatk4-human-genome
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:33 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:34 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:34 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:35 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine in-memory-database-redis-redis-benchmark
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:36 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:36 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:37 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:37 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine middleware-dubbo-dubbo-benchmark
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:38 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:39 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:39 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:40 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine storage-ceph-vdbench-hdd
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:41 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:41 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:42 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:42 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine storage-ceph-vdbench-ssd
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:43 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:44 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:44 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:45 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine virtualization-consumer-cloud-olc
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:46 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:46 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:47 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:48 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine virtualization-mariadb-2p-tpcc-c3
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:48 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:49 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:50 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:50 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine virtualization-mariadb-4p-tpcc-c3
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:51 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:51 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:52 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:53 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine web-apache-traffic-server-spirent-pingpo
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:54 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:54 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:55 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:55 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine web-nginx-http-long-connection
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:56 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:57 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:41:57 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:41:58 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ atune-adm undefine web-nginx-https-short-connection
+ CHECK_RESULT 1 0 0 'undefine command execution failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='undefine command execution failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'undefine command execution failed'
+ LOG_ERROR 'undefine command execution failed'
+ message='undefine command execution failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'undefine command execution failed'
Thu May 25 22:41:59 2023 - ERROR - undefine command execution failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 48'
+ message='oe_test_service_atuned_04.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 48'
Thu May 25 22:41:59 2023 - ERROR - oe_test_service_atuned_04.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 0 0 'delete failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Thu May 25 22:42:00 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 50'
+ message='oe_test_service_atuned_04.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 50'
Thu May 25 22:42:00 2023 - ERROR - oe_test_service_atuned_04.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<46 ))
+ array=("$SPECIAL_CHARACTERS" "$ULTRA_LONG_CHARACTERS" "")
+ (( i=0 ))
+ (( i<3 ))
+ atune-adm undefine '~\!@#%^*'
+ case ${array[i]} in
+ CHECK_RESULT 1 1 0 'The status code is not 1'
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log='The status code is not 1'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ grep 'input:.* is invalid' temp.log
input:~\!@#%^* is invalid
+ CHECK_RESULT 0 1 0 'Cyclic failure'
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log='Cyclic failure'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n 'Cyclic failure'
+ LOG_ERROR 'Cyclic failure'
+ message='Cyclic failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Cyclic failure'
Thu May 25 22:42:01 2023 - ERROR - Cyclic failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 67'
+ message='oe_test_service_atuned_04.sh line 67'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 67'
Thu May 25 22:42:02 2023 - ERROR - oe_test_service_atuned_04.sh line 67
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<3 ))
+ atune-adm undefine 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
+ case ${array[i]} in
+ CHECK_RESULT 1 0 0 'The status code is not 0'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The status code is not 0'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The status code is not 0'
+ LOG_ERROR 'The status code is not 0'
+ message='The status code is not 0'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The status code is not 0'
Thu May 25 22:42:03 2023 - ERROR - The status code is not 0
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 61'
+ message='oe_test_service_atuned_04.sh line 61'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 61'
Thu May 25 22:42:03 2023 - ERROR - oe_test_service_atuned_04.sh line 61
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'only self defined type can be deleted' temp.log
+ CHECK_RESULT 1 1 0 'Cyclic failure'
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log='Cyclic failure'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ (( i++ ))
+ (( i<3 ))
+ atune-adm undefine
+ case ${array[i]} in
+ CHECK_RESULT 1 1 0 'only self defined type can be deleted'
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log='only self defined type can be deleted'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ grep 'Incorrect Usage.' temp.log
Incorrect Usage.
+ CHECK_RESULT 0 1 0 'Cyclic failure'
+ actual_result=0
+ expect_result=1
+ mode=0
+ error_log='Cyclic failure'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 1x
+ test -n 'Cyclic failure'
+ LOG_ERROR 'Cyclic failure'
+ message='Cyclic failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Cyclic failure'
Thu May 25 22:42:04 2023 - ERROR - Cyclic failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_atuned_04.sh line 67'
+ message='oe_test_service_atuned_04.sh line 67'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_atuned_04.sh line 67'
Thu May 25 22:42:05 2023 - ERROR - oe_test_service_atuned_04.sh line 67
+ '[' 0 -eq 1 ']'
+ return 0
+ (( i++ ))
+ (( i<3 ))
+ CASE_RESULT 0
+ case_re=0
+ test -z 97
+ test 97 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu May 25 22:42:05 2023 - ERROR - failed to execute the case.
+ exit 97
+ post_test
+ clean_autund
+ systemctl stop atuned
+ systemctl stop atune-engine
+ rm -fr /etc/atuned/atuned.cnf /etc/atuned/atuned.cnf
+ mv /etc/atuned/atuned.cnf.bak /etc/atuned/atuned.cnf
+ mv /etc/atuned/engine.cnf.bak /etc/atuned/engine.cnf
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpz_wmvnm1 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpz_wmvnm1
+ '[' 0 -ne 0 ']'
+ rm -fr temp.log
