+ '﻿#!/usr/bin/bash'
oe_test_gcc.sh: line 1: ﻿#!/usr/bin/bash: No such file or directory
+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Mon May 26 09:26:07 2025 - INFO  - Start environment preparation.
+ mkdir /tmp/test
+ path=/tmp/test
+ cat
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Mon May 26 09:26:07 2025 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Mon May 26 09:26:07 2025 - INFO  - Start testing...
+ gcc -o /tmp/test/a.out /tmp/test/test1.c
oe_test_gcc.sh: line 39: gcc: command not found
+ ls /tmp/test/a.out
ls: cannot access '/tmp/test/a.out': No such file or directory
+ CHECK_RESULT 2 0 0 'gcc file fails'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='gcc file fails'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'gcc file fails'
+ LOG_ERROR 'gcc file fails'
+ message='gcc file fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gcc file fails'
Mon May 26 09:26:07 2025 - ERROR - gcc file fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 41'
+ message='oe_test_gcc.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 41'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ /tmp/test/a.out
+ CHECK_RESULT 127 0 0 'Compilation fails'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Compilation fails'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Compilation fails'
+ LOG_ERROR 'Compilation fails'
+ message='Compilation fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Compilation fails'
Mon May 26 09:26:07 2025 - ERROR - Compilation fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 43'
+ message='oe_test_gcc.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 43'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'hello world!' /tmp/test/tmp.1
+ CHECK_RESULT 1 0 0 'Compilation fails'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Compilation fails'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Compilation fails'
+ LOG_ERROR 'Compilation fails'
+ message='Compilation fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Compilation fails'
Mon May 26 09:26:07 2025 - ERROR - Compilation fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 45'
+ message='oe_test_gcc.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 45'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ gcc /tmp/test/test1.c -o /tmp/test/test2
oe_test_gcc.sh: line 47: gcc: command not found
+ ls /tmp/test/test2
ls: cannot access '/tmp/test/test2': No such file or directory
+ CHECK_RESULT 2 0 0 'gcc -o file fails'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='gcc -o file fails'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'gcc -o file fails'
+ LOG_ERROR 'gcc -o file fails'
+ message='gcc -o file fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gcc -o file fails'
Mon May 26 09:26:07 2025 - ERROR - gcc -o file fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 49'
+ message='oe_test_gcc.sh line 49'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 49'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 49
+ '[' 0 -eq 1 ']'
+ return 0
+ /tmp/test/test2
+ CHECK_RESULT 127 0 0 'test2 Compilation fails'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='test2 Compilation fails'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'test2 Compilation fails'
+ LOG_ERROR 'test2 Compilation fails'
+ message='test2 Compilation fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'test2 Compilation fails'
Mon May 26 09:26:07 2025 - ERROR - test2 Compilation fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 51'
+ message='oe_test_gcc.sh line 51'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 51'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 51
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'hello world!' /tmp/test/tmp.2
+ CHECK_RESULT 1 0 0 'nothingness hello word'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='nothingness hello word'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'nothingness hello word'
+ LOG_ERROR 'nothingness hello word'
+ message='nothingness hello word'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'nothingness hello word'
Mon May 26 09:26:07 2025 - ERROR - nothingness hello word
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 53'
+ message='oe_test_gcc.sh line 53'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 53'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 53
+ '[' 0 -eq 1 ']'
+ return 0
+ gcc -E /tmp/test/test1.c -o /tmp/test/test.i
oe_test_gcc.sh: line 55: gcc: command not found
+ ls /tmp/test/test.i
ls: cannot access '/tmp/test/test.i': No such file or directory
+ CHECK_RESULT 2 0 0 'gcc -E file fails'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='gcc -E file fails'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'gcc -E file fails'
+ LOG_ERROR 'gcc -E file fails'
+ message='gcc -E file fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gcc -E file fails'
Mon May 26 09:26:07 2025 - ERROR - gcc -E file fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 57'
+ message='oe_test_gcc.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 57'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ gcc -S /tmp/test/test.i -o /tmp/test/test.s
oe_test_gcc.sh: line 59: gcc: command not found
+ ls /tmp/test/test.s
ls: cannot access '/tmp/test/test.s': No such file or directory
+ CHECK_RESULT 2 0 0 'gcc -S file fails'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='gcc -S file fails'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'gcc -S file fails'
+ LOG_ERROR 'gcc -S file fails'
+ message='gcc -S file fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gcc -S file fails'
Mon May 26 09:26:07 2025 - ERROR - gcc -S file fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 61'
+ message='oe_test_gcc.sh line 61'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 61'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 61
+ '[' 0 -eq 1 ']'
+ return 0
+ gcc -c /tmp/test/test.s -o /tmp/test/test.o
oe_test_gcc.sh: line 63: gcc: command not found
+ ls /tmp/test/test.o
ls: cannot access '/tmp/test/test.o': No such file or directory
+ CHECK_RESULT 2 0 0 'gcc -c file fails'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='gcc -c file fails'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'gcc -c file fails'
+ LOG_ERROR 'gcc -c file fails'
+ message='gcc -c file fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gcc -c file fails'
Mon May 26 09:26:07 2025 - ERROR - gcc -c file fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 65'
+ message='oe_test_gcc.sh line 65'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 65'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 65
+ '[' 0 -eq 1 ']'
+ return 0
+ gcc /tmp/test/test.o -o /tmp/test/test1
oe_test_gcc.sh: line 67: gcc: command not found
+ ls /tmp/test/test1
ls: cannot access '/tmp/test/test1': No such file or directory
+ CHECK_RESULT 2 0 0 'tset1 Generate failure'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='tset1 Generate failure'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'tset1 Generate failure'
+ LOG_ERROR 'tset1 Generate failure'
+ message='tset1 Generate failure'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'tset1 Generate failure'
Mon May 26 09:26:07 2025 - ERROR - tset1 Generate failure
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 69'
+ message='oe_test_gcc.sh line 69'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 69'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 69
+ '[' 0 -eq 1 ']'
+ return 0
+ /tmp/test/test1
+ CHECK_RESULT 127 0 0 'test1 Compilation fails'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='test1 Compilation fails'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'test1 Compilation fails'
+ LOG_ERROR 'test1 Compilation fails'
+ message='test1 Compilation fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'test1 Compilation fails'
Mon May 26 09:26:07 2025 - ERROR - test1 Compilation fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 71'
+ message='oe_test_gcc.sh line 71'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 71'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 71
+ '[' 0 -eq 1 ']'
+ return 0
+ grep 'hello world!' /tmp/test/tmp.3
+ CHECK_RESULT 1 0 0 'test1 Compilation fails'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='test1 Compilation fails'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'test1 Compilation fails'
+ LOG_ERROR 'test1 Compilation fails'
+ message='test1 Compilation fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'test1 Compilation fails'
Mon May 26 09:26:07 2025 - ERROR - test1 Compilation fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 73'
+ message='oe_test_gcc.sh line 73'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 73'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 73
+ '[' 0 -eq 1 ']'
+ return 0
+ gcc -g /tmp/test/test1.c -o /tmp/test/test1_d
oe_test_gcc.sh: line 75: gcc: command not found
+ ls /tmp/test/test1_d
ls: cannot access '/tmp/test/test1_d': No such file or directory
+ CHECK_RESULT 2 0 0 'gcc -d file fails'
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log='gcc -d file fails'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n 'gcc -d file fails'
+ LOG_ERROR 'gcc -d file fails'
+ message='gcc -d file fails'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'gcc -d file fails'
Mon May 26 09:26:07 2025 - ERROR - gcc -d file fails
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_gcc.sh line 77'
+ message='oe_test_gcc.sh line 77'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_gcc.sh line 77'
Mon May 26 09:26:07 2025 - ERROR - oe_test_gcc.sh line 77
+ '[' 0 -eq 1 ']'
+ return 0
+ CASE_RESULT 0
+ case_re=0
+ test -z 13
+ test 13 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Mon May 26 09:26:08 2025 - ERROR - failed to execute the case.
+ exit 13
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Mon May 26 09:26:08 2025 - INFO  - start environment cleanup.
+ rm -rf /tmp/test
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Mon May 26 09:26:08 2025 - INFO  - Finish environment cleanup!
