+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Mon May 26 08:42:41 2025 - INFO  - Start to prepare the test environment.
+ auditctl rate_limit=0
+ auditctl backlog_wait_time=0
+ echo '
    #!/bin/bash
while true
do
   sudo ls /root/ > /dev/null
done'
+ chmod +777 ./audit_shell
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Mon May 26 08:42:41 2025 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Mon May 26 08:42:41 2025 - INFO  - Start to run test.
+ auditctl -s
+ ./audit_shell
+ CHECK_RESULT 0 0 0 'Check auditctl -s: failed!'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Check auditctl -s: failed!'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ grep -w backlog audit_log
++ awk '{print $2}'
+ backlog=0
++ grep -w backlog_limit audit_log
++ awk '{print $2}'
+ backlog_limit=64
+ '[' 0 -lt 64 ']'
+ CHECK_RESULT 0 0 0 'Backlog not increase indefinitely: failed!'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Backlog not increase indefinitely: failed!'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Mon May 26 08:42:41 2025 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Mon May 26 08:42:41 2025 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Mon May 26 08:42:41 2025 - INFO  - Start to restore the test environment.
+ rm -rf audit_shell audit_log
++ ps -ef
++ grep ./audit_shell
++ grep -v grep
++ awk '{print $2}'
+ kill -9
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Mon May 26 08:42:41 2025 - INFO  - End to restore the test environment.
sudo: unable to load /usr/lib64/libsss_sudo.so: /usr/lib64/libsss_sudo.so: cannot open shared object file: No such file or directory
sudo: unable to initialize SSS source. Is SSSD installed on your machine?
*repeat to line 2420633*