+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Fri May 26 06:47:22 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'atune-engine atune'
+ pkgs='atune-engine atune'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'atune-engine atune' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpos021kuz
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpos021kuz
++ lsblk
++ grep disk
++ awk 'NR==1{print $1}'
+ disk_name=vda
+ sed -i 's\disk = sda\disk = vda\g' /etc/atuned/atuned.cnf
+ sed -i 's\network = enp189s0f0\network = \g' /etc/atuned/atuned.cnf
+ sed -i 's\rest_tls = true\rest_tls = false\g' /etc/atuned/atuned.cnf
+ sed -i 's\engine_tls = true\engine_tls = false\g' /etc/atuned/atuned.cnf
+ sed -i 's\engine_tls = true\engine_tls = false\g' /etc/atuned/engine.cnf
+ systemctl start atuned.service
Failed to start atuned.service: Unit polkit.service not found.
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Fri May 26 06:48:00 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Fri May 26 06:48:00 2023 - INFO  - Start testing...
+ test_execution atune-engine.service
+ service=atune-engine.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-05-26 06:48:00'
+ test_restart atune-engine.service
+ service=atune-engine.service
+ systemctl restart atune-engine.service
Failed to restart atune-engine.service: Unit polkit.service not found.
+ CHECK_RESULT 5 0 0 'atune-engine.service restart failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='atune-engine.service restart failed'
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'atune-engine.service restart failed'
+ LOG_ERROR 'atune-engine.service restart failed'
+ message='atune-engine.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-engine.service restart failed'
Fri May 26 06:48:00 2023 - ERROR - atune-engine.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Fri May 26 06:48:00 2023 - ERROR - ../common/common_lib.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status atune-engine.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'atune-engine.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-engine.service restart failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-engine.service restart failed'
+ LOG_ERROR 'atune-engine.service restart failed'
+ message='atune-engine.service restart failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-engine.service restart failed'
Fri May 26 06:48:05 2023 - ERROR - atune-engine.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Fri May 26 06:48:05 2023 - ERROR - ../common/common_lib.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl stop atune-engine.service
+ CHECK_RESULT 0 0 0 'atune-engine.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='atune-engine.service stop failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status atune-engine.service
+ grep 'Active: inactive'
     Active: inactive (dead)
+ CHECK_RESULT 0 0 0 'atune-engine.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='atune-engine.service stop failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl start atune-engine.service
Failed to start atune-engine.service: Unit polkit.service not found.
+ CHECK_RESULT 5 0 0 'atune-engine.service start failed'
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log='atune-engine.service start failed'
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n 'atune-engine.service start failed'
+ LOG_ERROR 'atune-engine.service start failed'
+ message='atune-engine.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-engine.service start failed'
Fri May 26 06:48:10 2023 - ERROR - atune-engine.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Fri May 26 06:48:10 2023 - ERROR - ../common/common_lib.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status atune-engine.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'atune-engine.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-engine.service start failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-engine.service start failed'
+ LOG_ERROR 'atune-engine.service start failed'
+ message='atune-engine.service start failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-engine.service start failed'
Fri May 26 06:48:15 2023 - ERROR - atune-engine.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Fri May 26 06:48:15 2023 - ERROR - ../common/common_lib.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ test_enabled atune-engine.service
+ service=atune-engine.service
++ systemctl is-enabled atune-engine.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable atune-engine.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/atune-engine.service
+ find /etc/systemd/system/multi-user.target.wants/atune-engine.service
/etc/systemd/system/multi-user.target.wants/atune-engine.service
+ CHECK_RESULT 0 0 0 'atune-engine.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='atune-engine.service enable failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable atune-engine.service
Removed /etc/systemd/system/multi-user.target.wants/atune-engine.service.
+ find /etc/systemd/system/multi-user.target.wants/atune-engine.service
find: ‘/etc/systemd/system/multi-user.target.wants/atune-engine.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'atune-engine.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='atune-engine.service disable failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2023-05-26 06:48:00' -u atune-engine.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ CHECK_RESULT 1 0 1 'There is an error message for the log of atune-engine.service'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of atune-engine.service'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ test_reload atune-engine.service
+ service=atune-engine.service
+ systemctl start atune-engine.service
Failed to start atune-engine.service: Unit polkit.service not found.
+ systemctl reload atune-engine.service
+ grep 'Job type reload is not applicable'
Failed to reload atune-engine.service: Job type reload is not applicable for unit atune-engine.service.
+ CHECK_RESULT 0 0 0 'Job type reload is not applicable for unit atune-engine.service'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit atune-engine.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl status atune-engine.service
+ grep 'Active: active'
+ systemctl status atune-engine.service
+ grep 'inactive (dead)'
     Active: inactive (dead)
+ systemctl status atune-engine.service
+ grep 'Condition check'
+ grep skip
+ CHECK_RESULT 1 0 0 'atune-engine.service reload causes the service status to change'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atune-engine.service reload causes the service status to change'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atune-engine.service reload causes the service status to change'
+ LOG_ERROR 'atune-engine.service reload causes the service status to change'
+ message='atune-engine.service reload causes the service status to change'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'atune-engine.service reload causes the service status to change'
Fri May 26 06:48:15 2023 - ERROR - atune-engine.service reload causes the service status to change
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 95'
+ message='../common/common_lib.sh line 95'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 95'
Fri May 26 06:48:15 2023 - ERROR - ../common/common_lib.sh line 95
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Fri May 26 06:48:15 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 5
+ test 5 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri May 26 06:48:15 2023 - ERROR - failed to execute the case.
+ exit 5
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri May 26 06:48:15 2023 - INFO  - start environment cleanup.
+ systemctl stop atuned.service
+ sed -i 's\disk = vda\disk = sda\g' /etc/atuned/atuned.cnf
+ sed -i 's\network = \network = enp189s0f0\g' /etc/atuned/atuned.cnf
+ sed -i 's\rest_tls = false\rest_tls = true\g' /etc/atuned/atuned.cnf
+ sed -i 's\engine_tls = false\engine_tls = true\g' /etc/atuned/atuned.cnf
+ sed -i 's\engine_tls = false\engine_tls = true\g' /etc/atuned/engine.cnf
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpos021kuz ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpos021kuz
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Fri May 26 06:48:18 2023 - INFO  - Finish environment cleanup!
