+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Mon May 26 09:23:00 2025 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL iotop
+ pkgs=iotop
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs iotop --node 1 --tempfile ''
Mon May 26 09:23:01 2025 - INFO  - pkgs:(iotop) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ echo '#!/bin/bash
while true
do
   echo '\''iotop test'\''>test
done'
+ chmod u+x iotoptest
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Mon May 26 09:23:01 2025 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Mon May 26 09:23:01 2025 - INFO  - Start to run test.
+ CHECK_RESULT 0 0 0 'Execute i/o process:failed'
+ actual_result=0
+ ./iotoptest
+ expect_result=0
+ mode=0
+ error_log='Execute i/o process:failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ iotop -o -b -n 2 -d 10
+ grep iotoptest
 715376 be/4 root        0.00 B/s   23.00 M/s  ?unavailable?  bash ./iotoptest
 715376 be/4 root        0.00 B/s   20.66 M/s  ?unavailable?  bash ./iotoptest
+ CHECK_RESULT 0 0 0 'Failed to check the running i/o process'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to check the running i/o process'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ iotop -o -b -n 1 -d 10
++ wc -l
+ running_io_total=5
++ iotop -b -n 1 -d 10
++ wc -l
+ all_io_total=197
+ test 197
+ CHECK_RESULT 0 0 0 'Failed to check the all i/o process!'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed to check the all i/o process!'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Mon May 26 09:23:11 2025 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Mon May 26 09:23:11 2025 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Mon May 26 09:23:11 2025 - INFO  - Start to restore the test environment.
+ DNF REMOVE
oe_test_user_debug_iotop_03.sh: line 48: DNF: command not found
++ ps -ef
++ grep iotoptest
++ grep -v grep
++ awk '{print $2}'
+ kill -9 715376
+ rm -rf test iotoptest
oe_test_user_debug_iotop_03.sh: line 46: 715376 Killed                  ./iotoptest
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Mon May 26 09:23:11 2025 - INFO  - End to restore the test environment.
